---
# tasks file for jenkins

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key
          
- name: Add Jenkins repository
  yum_repository:
    name: jenkins
    description: jenkins repository
    baseurl: http://pkg.jenkins.io/redhat
    gpgcheck: yes

- name: Install Java
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Install Jenkins
  yum:
    name: jenkins
    enablerepo: jenkins
    state: present

- name: Start Jenkins
  service:
    name: jenkins
    enabled: yes
    state: started

